### ISSUE TITLE
/api/oas-doc.yaml is missing from 0.2.0

### ISSUE THREAD

**Issue by achingbrain** [ipfs-shipyard/js-mock-ipfs-pinning-service#12]
I'm seeing errors similar to:

```
Test Node.js
ENOENT: no such file or directory, open '/path/to/node_modules/mock-ipfs-pinning-service/api/oas-doc.yaml'
```

Indeed, this 404s: https://unpkg.com/mock-ipfs-pinning-service@0.2.0/api/oas-doc.yaml

**Comment by lidel** [comment]
I think this is because package-lock was outdated.
This repo uses yarn, #8 should fix it

**Comment by lidel** [comment]
Hm.. no, seems to be something else, reopening.

**Comment by lidel** [comment]
Ok, so https://unpkg.com/mock-ipfs-pinning-service@0.3.0/api/oas-doc.yaml exists now, 
but running it  via `npx` is still broken for me – filled https://github.com/ipfs-shipyard/js-mock-ipfs-pinning-service/issues/16
