### ISSUE TITLE
Require Authorization header

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/js-mock-ipfs-pinning-service#2]
Mock should:
- return 401 Unauthorized error when `Authorization: Bearer <access-token>` is missing or invalid
- make it possible to pass `<access-token>` during its start 

(We need this if we want to replace [rb-pinning-service-api](https://github.com/ipfs-shipyard/rb-pinning-service-api) in go-ipfs tests)

cc @Gozala

**Comment by Gozala** [comment]
Fixed by 84f6c1c278e033047927b4e869ab5f7a834e047c Note you need to provide `--token secret` in cli or `setup({ token: 'secret' })` to activate auth, otherwise it will just accept requests without verification.
