### ISSUE TITLE
Disable support for comma separated cid params

### ISSUE THREAD

**Issue by Gozala** [ipfs-shipyard/js-mock-ipfs-pinning-service#3]
Since go-ipfs no longer supports comma separated params https://github.com/ipfs/go-ipfs/pull/7863 we should remove a support for that style here as well.

**Comment by lidel** [comment]
I don't believe that is  true. 

- Comma separated notation was removed from go-ipfs'  `/api/v0/pin/remote` HTTP API, but will still be supported in CLI params in `ipfs pin remote --help`
- This project implements `/pins` from https://ipfs.github.io/pinning-services-api-spec/ and comma separated cids are still in the spec, so this cna be closed (we won't change the Pinnin Service API spec)
